#!/usr/bin/env node
// Generate docs/TEST-CATALOG.md from the test files. The test TITLES are the
// living spec: write descriptive `describe(...)` / `it(...)` / `test(...)` titles
// and they become the catalog automatically. Run: `pnpm test:catalog`
// (CI can run it with --check to fail when the catalog is stale.)

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "../..");
const OUT = join(ROOT, "docs", "TEST-CATALOG.md");

const LAYERS = [
  { name: "Unit", blurb: "Pure logic, no DB (Vitest). `pnpm test`", match: (f) => f.endsWith(".test.ts") && !f.endsWith(".int.test.ts") && !f.includes("/e2e/") },
  { name: "Integration", blurb: "Real Postgres + RLS (Vitest). `pnpm test:int`", match: (f) => f.endsWith(".int.test.ts") },
  { name: "End-to-end", blurb: "Playwright, desktop + mobile. `pnpm test:e2e`", match: (f) => f.includes("/e2e/") && f.endsWith(".spec.ts") },
];

const SKIP_DIRS = new Set(["node_modules", ".next", ".turbo", "dist", ".git"]);

async function walk(dir, acc = []) {
  for (const ent of await readdir(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(ent.name)) continue;
    const full = join(dir, ent.name);
    if (ent.isDirectory()) await walk(full, acc);
    else if (ent.name.endsWith(".test.ts") || ent.name.endsWith(".spec.ts")) acc.push(full);
  }
  return acc;
}

const CALL = /\b(describe|it|test)\s*\(\s*(["'`])([\s\S]*?)\2/;

// Extract describe/it/test titles with nesting inferred from indentation.
function parse(src) {
  const lines = src.split("\n");
  const out = [];
  const stack = []; // { indent, kind }
  for (const line of lines) {
    const m = line.match(CALL);
    if (!m) continue;
    const indent = line.match(/^\s*/)[0].length;
    while (stack.length && stack[stack.length - 1].indent >= indent) stack.pop();
    const kind = m[1];
    const title = m[3].replace(/\s+/g, " ").trim();
    out.push({ depth: stack.length, kind, title });
    if (kind === "describe") stack.push({ indent });
  }
  return out;
}

// Leading // or /* */ comment block at the top of the file → section intro.
function header(src) {
  const lines = src.split("\n");
  const buf = [];
  for (const raw of lines) {
    const l = raw.trim();
    if (l.startsWith("//")) buf.push(l.replace(/^\/\/\s?/, ""));
    else if (l.startsWith("/*") || l.startsWith("*") || l.endsWith("*/")) buf.push(l.replace(/^\/\*+|\*+\/$|^\*\s?/g, "").trim());
    else if (l === "") {
      if (buf.length) break;
    } else break;
  }
  return buf.filter(Boolean).join(" ").trim();
}

const files = (await walk(ROOT)).sort();
let totalCases = 0;
const sections = [];

for (const layer of LAYERS) {
  const layerFiles = files.filter((f) => layer.match(f.split("\\").join("/")));
  if (layerFiles.length === 0) continue;
  let layerCases = 0;
  const parts = [];
  for (const file of layerFiles) {
    const src = await readFile(file, "utf8");
    const entries = parse(src);
    const cases = entries.filter((e) => e.kind !== "describe").length;
    layerCases += cases;
    const rel = relative(ROOT, file);
    const intro = header(src);
    const body = entries
      .map((e) => {
        const pad = "  ".repeat(e.depth);
        return e.kind === "describe" ? `${pad}- **${e.title}**` : `${pad}- [ ] ${e.title}`;
      })
      .join("\n");
    parts.push(`#### \`${rel}\` — ${cases} case${cases === 1 ? "" : "s"}${intro ? `\n\n_${intro}_` : ""}\n\n${body}`);
  }
  totalCases += layerCases;
  sections.push(`### ${layer.name} — ${layerCases} cases\n\n${layer.blurb}\n\n${parts.join("\n\n")}`);
}

const md = `# Test Catalog

> Auto-generated by \`pnpm test:catalog\` from the test files. Do not edit by hand —
> the \`describe\`/\`it\`/\`test\` titles in the specs are the source of truth.

**${totalCases} test cases** across ${files.length} files.

${sections.join("\n\n---\n\n")}
`;

if (process.argv.includes("--check")) {
  const existing = await readFile(OUT, "utf8").catch(() => "");
  if (existing.trim() !== md.trim()) {
    console.error("TEST-CATALOG.md is stale. Run `pnpm test:catalog`.");
    process.exit(1);
  }
  console.log("Test catalog is up to date.");
} else {
  await writeFile(OUT, md);
  console.log(`Wrote ${relative(ROOT, OUT)} — ${totalCases} cases across ${files.length} files.`);
}
